"""create prisoners table

Revision ID: b9f2c5fef1ae
Revises: 
Create Date: 2026-09-01 00:48:36.873687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9f2c5fef1ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prisoners',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.Column('original_release_date', sa.Date(), nullable=False),
    sa.Column('updated_release_date', sa.Date(), nullable=False),
    sa.Column('books_counter', sa.Integer(), nullable=False),
    sa.Column('current_year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prisoners')
    # ### end Alembic commands ###
