"""create Study books and dayOfwork

Revision ID: c3a1dd9e8c0b
Revises: 5e2b3dc62c55
Create Date: 2026-09-01 01:06:29.118198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3a1dd9e8c0b'
down_revision = '5e2b3dc62c55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('days_of_work',
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('prisoner_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['prisoner_id'], ['prisoners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('studies',
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('prisoner_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['prisoner_id'], ['prisoners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('studies')
    op.drop_table('days_of_work')
    # ### end Alembic commands ###
